name: Docker Image CI
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: publish-v1
        uses: versicherungskammer/multi-platform-docker-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          email: auto
          build-args: "APP_VERSION=v1"
          additional-tags: "v1"
          auto-tags: branch-name
      - name: publish-v2
        uses: versicherungskammer/multi-platform-docker-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          email: auto
          build-args: "APP_VERSION=v2"
          additional-tags: "v2"
          auto-tags: branch-name
      - name: publish-blue
        uses: versicherungskammer/multi-platform-docker-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          email: auto
          build-args: "APP_VERSION=v1 APP_PICTURE=blue.jpg"
          additional-tags: "blue"
          auto-tags: branch-name
      - name: publish-green
        uses: versicherungskammer/multi-platform-docker-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          email: auto
          build-args: "APP_VERSION=v1 APP_PICTURE=green.jpg"
          additional-tags: "green"
          auto-tags: branch-name
      - name: publish-canary
        uses: versicherungskammer/multi-platform-docker-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          email: auto
          build-args: "APP_VERSION=v1 APP_PICTURE=canary.jpg"
          additional-tags: "canary"
          auto-tags: branch-name
